# Generated by Django 5.2.7 on 2025-11-02 23:08

import django.db.models.deletion
from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    """Create default categories for kitchen items."""
    Category = apps.get_model('inventory', 'Category')
    default_categories = [
        ('Produce', 'Fresh fruits and vegetables'),
        ('Dairy', 'Milk, cheese, yogurt, and other dairy products'),
        ('Pantry', 'Dry goods and canned items'),
        ('Meat', 'Beef, pork, chicken, and other meats'),
        ('Spices', 'Herbs, seasonings, and spices'),
        ('Frozen', 'Frozen foods and ice cream'),
        ('Other', 'Miscellaneous items')
    ]
    for name, description in default_categories:
        Category.objects.get_or_create(
            name=name,
            defaults={'description': description}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_mealcost_purchaserecord_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.category'),
        ),
    ]
