# Generated by Django 5.2.7 on 2025-11-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_user_item_created_by_item_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.CharField(blank=True, help_text='Supplier/Vendor name', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit in KES', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (Kg)'), ('litre', 'Litre (L)'), ('piece', 'Piece'), ('packet', 'Packet'), ('dozen', 'Dozen'), ('bale', 'Bale')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receive Delivery'), ('issue', 'Use Item'), ('writeoff', 'Waste/Spillage')], max_length=10),
        ),
    ]
