# Generated by Django 5.2.7 on 2025-11-03 08:13

from django.db import migrations


def update_movement_types(apps, schema_editor):
    """
    Update old movement types to new ones.
    - 'issue' -> 'usage' (tracking only)
    - 'writeoff' -> 'waste' (tracking only)
    """
    StockMovement = apps.get_model('inventory', 'StockMovement')
    
    # Update issue to usage
    StockMovement.objects.filter(movement_type='issue').update(movement_type='usage')
    
    # Update writeoff to waste  
    StockMovement.objects.filter(movement_type='writeoff').update(movement_type='waste')


def reverse_update_movement_types(apps, schema_editor):
    """
    Reverse the migration - change back to old types.
    """
    StockMovement = apps.get_model('inventory', 'StockMovement')
    
    # Update usage back to issue
    StockMovement.objects.filter(movement_type='usage').update(movement_type='issue')
    
    # Update waste back to writeoff
    StockMovement.objects.filter(movement_type='waste').update(movement_type='writeoff')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_bitz_kitchen_setup'),
    ]

    operations = [
        migrations.RunPython(update_movement_types, reverse_update_movement_types),
    ]
