# Generated by Django 5.2.7 on 2025-11-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_fix_movement_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Name of person assigned to receive delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='requisition',
            name='date_received',
            field=models.DateTimeField(blank=True, help_text='Date when delivery was confirmed received', null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='received_by',
            field=models.CharField(blank=True, help_text='Name of person who confirmed receipt', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('awaiting_delivery', 'Awaiting Delivery'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receive Delivery'), ('usage', 'Track Usage (Cooking)'), ('waste', 'Track Waste/Spillage')], max_length=10),
        ),
    ]
