# Generated by Django 5.2.7 on 2025-11-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_requisition_assigned_to_requisition_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='quantity_received',
            field=models.IntegerField(blank=True, help_text='Actual quantity received (must be <= requested)', null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='receipt_notes',
            field=models.TextField(blank=True, help_text='Notes explaining any quantity discrepancies'),
        ),
    ]
