# Generated by Django 5.2.7 on 2025-11-03 12:11

from django.db import migrations


def update_approved_to_awaiting_delivery(apps, schema_editor):
    """Update old 'approved' requisitions to 'awaiting_delivery'"""
    Requisition = apps.get_model('inventory', 'Requisition')
    Requisition.objects.filter(status='approved').update(status='awaiting_delivery')


def reverse_update(apps, schema_editor):
    """Reverse: Set awaiting_delivery back to approved"""
    Requisition = apps.get_model('inventory', 'Requisition')
    # Note: This will lose information about which were actually awaiting delivery
    # but is needed for migration rollback
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_item_unique_item_name'),
    ]

    operations = [
        migrations.RunPython(update_approved_to_awaiting_delivery, reverse_update),
    ]
