# Generated by Django 5.2.7 on 2025-11-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_requisition_approved_by_money_received_by'),
        ('inventory', '0014_requisition_estimated_cost'),
    ]

    operations = [
    ]
